### ISSUE TITLE
failure

### ISSUE THREAD

**Issue by ramezaniivar** [khjde1207/tesseract_ocr#44]
After releasing the application on Google Play, I noticed this error on some phones when extracting text from the image:

io.paratoner.flutter_tesseract_ocr.FlutterTesseractOcrPlugin.onDetachedFromEngine

java.lang.NullPointerException

**Comment by ramezaniivar** [comment]
firebase crashlytics:

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.googlecode.tesseract.android.TessBaseAPI.f()' on a null object reference
       at v6.a.i(:10)
       at io.flutter.embedding.engine.c.v(:122)
       at io.flutter.embedding.engine.c.w(:16)
       at io.flutter.embedding.engine.c.x(:11)
       at io.flutter.embedding.engine.c.k(:10)
       at io.flutter.embedding.engine.a.g(:31)
       at io.flutter.embedding.android.f.u(:105)
       at io.flutter.embedding.android.e.onDestroy(:18)
       at android.app.Activity.performDestroy(Activity.java:7218)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4398)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4429)
       at android.app.ActivityThread.-wrap5()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by ramezaniivar** [comment]
https://github.com/adaptech-cz/Tesseract4Android/issues/64#issuecomment-1956424994

**Comment by rahuljallapalli** [comment]
Did any one found solution for this ?
